// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppMovies.Data;

#nullable disable

namespace WebAppMovies.Migrations
{
    [DbContext(typeof(MoviesDbContext))]
    [Migration("20260422190343_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebAppMovies.Models.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a2b3c4d-5e6f-47a8-9b0c-1d2e3f4a5b6c"),
                            FirstName = "Michelle",
                            LastName = "Yeoh"
                        },
                        new
                        {
                            Id = new Guid("2b3c4d5e-6f7a-48b9-0c1d-2e3f4a5b6c7d"),
                            FirstName = "Brad",
                            LastName = "Pitt"
                        },
                        new
                        {
                            Id = new Guid("3c4d5e6f-7a8b-49c0-1d2e-3f4a5b6c7d8e"),
                            FirstName = "Jenna",
                            LastName = "Ortega"
                        });
                });

            modelBuilder.Entity("WebAppMovies.Models.Director", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f1c9b2a-7c4e-4d1a-9a2b-1c2d3e4f5a61"),
                            FirstName = "Steven",
                            LastName = "Spielberg"
                        },
                        new
                        {
                            Id = new Guid("7a8d2c3b-1e4f-4a9b-8c2d-5e6f7a8b9c10"),
                            FirstName = "Kathryn",
                            LastName = "Bigelow"
                        },
                        new
                        {
                            Id = new Guid("9c2e1a7b-3d4f-4b8a-9e1c-2d3f4a5b6c72"),
                            FirstName = "Quentin",
                            LastName = "Tarantino"
                        });
                });

            modelBuilder.Entity("WebAppMovies.Models.Kind", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Kinds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a2b3c4d-5e6f-47a8-9b0c-111111111111"),
                            Description = "Action"
                        },
                        new
                        {
                            Id = new Guid("2b3c4d5e-6f7a-48b9-0c1d-222222222222"),
                            Description = "Comédie"
                        },
                        new
                        {
                            Id = new Guid("3c4d5e6f-7a8b-49c0-1d2e-333333333333"),
                            Description = "Drame"
                        },
                        new
                        {
                            Id = new Guid("7a8d2c3b-1e4f-4a9b-8c2d-444444444444"),
                            Description = "Horreur"
                        },
                        new
                        {
                            Id = new Guid("9c2e1a7b-3d4f-4b8a-9e1c-555555555555"),
                            Description = "Science-fiction"
                        });
                });

            modelBuilder.Entity("WebAppMovies.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("WebAppMovies.Models.MovieActor", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("char(36)");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActors");
                });

            modelBuilder.Entity("WebAppMovies.Models.MovieKind", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("KindId")
                        .HasColumnType("char(36)");

                    b.HasKey("MovieId", "KindId");

                    b.HasIndex("KindId");

                    b.ToTable("MovieKinds");
                });

            modelBuilder.Entity("WebAppMovies.Models.Movie", b =>
                {
                    b.HasOne("WebAppMovies.Models.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("WebAppMovies.Models.MovieActor", b =>
                {
                    b.HasOne("WebAppMovies.Models.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppMovies.Models.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("WebAppMovies.Models.MovieKind", b =>
                {
                    b.HasOne("WebAppMovies.Models.Kind", "Kind")
                        .WithMany("MovieKinds")
                        .HasForeignKey("KindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppMovies.Models.Movie", "Movie")
                        .WithMany("MovieKinds")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kind");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("WebAppMovies.Models.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("WebAppMovies.Models.Director", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("WebAppMovies.Models.Kind", b =>
                {
                    b.Navigation("MovieKinds");
                });

            modelBuilder.Entity("WebAppMovies.Models.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("MovieKinds");
                });
#pragma warning restore 612, 618
        }
    }
}
